-- MySQL Script generated by MySQL Workbench
-- Sun Jan 17 15:23:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema automob
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema automob
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `automob` DEFAULT CHARACTER SET utf8 ;
USE `automob` ;

-- -----------------------------------------------------
-- Table `automob`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `automob`.`car` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plate` VARCHAR(7) NOT NULL,
  `brand` VARCHAR(40) NOT NULL,
  `color` VARCHAR(30) NOT NULL,
  `isInUse` TINYINT NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL,
  `deletedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `automob`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `automob`.`driver` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `isUsingCar` TINYINT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NULL,
  `deletedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `automob`.`driving`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `automob`.`driving` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `car_id` INT NOT NULL,
  `driver_id` INT NOT NULL,
  `startedAt` DATETIME NOT NULL,
  `endedAt` DATETIME NULL,
  `reason` VARCHAR(200) NOT NULL,
  INDEX `fk_car_has_driver_driver1_idx` (`driver_id` ASC),
  INDEX `fk_car_has_driver_car_idx` (`car_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_car_has_driver_car`
    FOREIGN KEY (`car_id`)
    REFERENCES `automob`.`car` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_car_has_driver_driver1`
    FOREIGN KEY (`driver_id`)
    REFERENCES `automob`.`driver` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
